apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: thalessn/gitopsfc
  newTag: e05da18c3c2cd78ee42ab4948c58ed96be5d432d
